//tableNames.ts

export const ETableName = {
    ActantGrammarCases: "ActantGrammarCases",
    ActantGroups: "ActantGroups",
    ActantPositions: "ActantPositions",
    ActantTypes: "ActantTypes",
    Classifiers: "Classifiers",
    DerivationFormulasQuery: "DerivationFormulasQuery",
    DerivationTypes: "DerivationTypes",
    GrammarCases: "GrammarCases",
    InflectionBlocks: "InflectionBlocks",
    InflectionTypes: "InflectionTypes",
    IssueKinds: "IssueKinds",
    IssuePriorities: "IssuePriorities",
    IssueStatuses: "IssueStatuses",
    MmorphemeGroups: "MmorphemeGroups",
    MorphemeGroups: "MorphemeGroups",
    MorphemeRanges: "MorphemeRanges",
    MorphemeRangesByDerivationTypes: "MorphemeRangesByDerivationTypes",
    MorphemeRangesByInflectionBlocks: "MorphemeRangesByInflectionBlocks",
    Morphemes: "Morphemes",
    MorphemesQuery: "MorphemesQuery",
    MorphPhoneticsOccasion: "MorphPhoneticsOccasion",
    MorphPhoneticsOption: "MorphPhoneticsOption",
    NounNumbers: "NounNumbers",
    NounParadigmNamesQuery: "NounParadigmNamesQuery",
    NounParadigmRows: "NounParadigmRows",
    NounParadigms: "NounParadigms",
    PersonVariabilityTypes: "PersonVariabilityTypes",
    PhoneticsChanges: "PhoneticsChanges",
    PhoneticsChangesQuery: "PhoneticsChangesQuery",
    PhoneticsOptionDetails: "PhoneticsOptionDetails",
    PhoneticsOptions: "PhoneticsOptions",
    PhoneticsTypeProhibitions: "PhoneticsTypeProhibitions",
    PhoneticsTypes: "PhoneticsTypes",
    Pronouns: "Pronouns",
    VerbNumbers: "VerbNumbers",
    VerbParadigmNamesQuery: "VerbParadigmNamesQuery",
    VerbParadigms: "VerbParadigms",
    VerbPersonMarkerParadigmNamesQuery: "VerbPersonMarkerParadigmNamesQuery",
    VerbPersonMarkerParadigmRows: "VerbPersonMarkerParadigmRows",
    VerbPersonMarkerParadigms: "VerbPersonMarkerParadigms",
    VerbPersons: "VerbPersons",
    VerbPluralityTypes: "VerbPluralityTypes",
    VerbRowFilters: "VerbRowFilters",
    VerbRowParadigmRows: "VerbRowParadigmRows",
    VerbRows: "VerbRows",
    VerbSeries: "VerbSeries",
    VerbTransitions: "VerbTransitions",
    VerbTypes: "VerbTypes",
} as const;

export type ETableName = (typeof ETableName)[keyof typeof ETableName];
